services:
  web:
    container_name: template-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /app/packages/client/node_modules
      - /app/packages/client/.next
      - .:/app
